language: python
dist: bionic
python:
- '3.5'
- '3.6'
env:
- DJANGO="Django>=1.11,<1.12.0"
- DJANGO="Django>=2.2,<2.3"
install:
- pip install -q $DJANGO
- pip install -r test_reqs.txt
- pip install -q -e .
script:
- flake8 courseaffils runtests.py --max-complexity=12 --exclude=*/migrations/*.py
- python runtests.py
