language: python
sudo: false
python:
  - "2.7"
  - "3.5"
env:
  - DJANGO="Django>=1.8.0,<1.9.0"
  - DJANGO="Django>=1.9.0,<1.10.0"
install:
  - pip install -q $DJANGO
  - pip install -r test_reqs.txt
  - pip install -q -e .
script:
  - flake8 courseaffils runtests.py --max-complexity=14
  - python runtests.py
notifications:
  slack: ccnmtl:GizSNscLWJLldjQrffB8mwgm
