language: python
sudo: false
python:
  - "2.7"
install:
  - pip install -r test_reqs.txt
  - pip install -q -e .
script:
  - flake8 courseaffils runtests.py
  - python runtests.py
notifications:
  slack: ccnmtl:GizSNscLWJLldjQrffB8mwgm
